"""基金集合静态元信息（由 list_fund_collections 迁移而来）"""

FUND_COLLECTION_METADATA = {
    'fund_name_em': {
        'display_name': '基金基本信息',
        'description': '东方财富网所有基金的基本信息，包括基金代码、简称、类型等',
        'route': '/funds/collections/fund_name_em',
        'order': 0,
    },
    'fund_basic_info': {
        'display_name': '雪球基金基本信息',
        'description': '雪球基金-基金详情，包括成立时间、最新规模、基金经理、评级等',
        'route': '/funds/collections/fund_basic_info',
        'order': 1,
    },
    'fund_info_index_em': {
        'display_name': '指数型基金基本信息',
        'description': '东方财富网-指数型基金基本信息，包括单位净值、日期、各周期业绩、手续费、起购金额、跟踪标的和方式等',
        'route': '/funds/collections/fund_info_index_em',
        'order': 2,
    },
    'fund_ranking': {
        'display_name': '基金排名',
        'description': '基金的业绩排名数据',
        'route': '/funds/collections/fund_ranking',
        'order': 4,
    },
    'fund_purchase_status': {
        'display_name': '基金申购状态',
        'description': '东方财富网-天天基金网-基金数据-基金申购状态，包括申购赎回状态、手续费、购买起点等',
        'route': '/funds/collections/fund_purchase_status',
        'order': 5,
    },
    'fund_etf_spot_em': {
        'display_name': 'ETF基金实时行情-东财',
        'description': '东方财富网-ETF实时行情数据，包括最新价、涨跌幅、成交量、资金流向等',
        'route': '/funds/collections/fund_etf_spot_em',
        'order': 6,
    },
    'fund_etf_spot_ths': {
        'display_name': 'ETF基金实时行情-同花顺',
        'description': '同花顺-ETF实时行情数据，包括净值、增长率、申赎状态等',
        'route': '/funds/collections/fund_etf_spot_ths',
        'order': 7,
    },
    'fund_lof_spot_em': {
        'display_name': 'LOF基金实时行情-东财',
        'description': '东方财富网-LOF实时行情数据，包括最新价、涨跌幅、成交量、市值等',
        'route': '/funds/collections/fund_lof_spot_em',
        'order': 8,
    },
    'fund_spot_sina': {
        'display_name': '基金实时行情-新浪',
        'description': '新浪财经-基金实时行情数据，支持封闭式基金、ETF基金、LOF基金三种类型',
        'route': '/funds/collections/fund_spot_sina',
        'order': 9,
    },
    'fund_etf_hist_min_em': {
        'display_name': 'ETF基金分时行情-东财',
        'description': '东方财富网-ETF 分时行情数据，支持按代码、时间周期、复权方式查询近期分钟级行情',
        'route': '/funds/collections/fund_etf_hist_min_em',
        'order': 10,
    },
    'fund_lof_hist_min_em': {
        'display_name': 'LOF基金分时行情-东财',
        'description': '东方财富网-LOF 分时行情数据，支持按代码、时间周期、复权方式查询近期分钟级行情',
        'route': '/funds/collections/fund_lof_hist_min_em',
        'order': 11,
    },
    'fund_etf_hist_em': {
        'display_name': 'ETF基金历史行情-东财',
        'description': '东方财富网-ETF 历史行情数据，支持按代码、周期（日/周/月）、复权方式查询历史K线数据',
        'route': '/funds/collections/fund_etf_hist_em',
        'order': 12,
    },
    'fund_lof_hist_em': {
        'display_name': 'LOF基金历史行情-东财',
        'description': '东方财富网-LOF 历史行情数据，支持按代码、周期（日/周/月）、复权方式查询历史K线数据',
        'route': '/funds/collections/fund_lof_hist_em',
        'order': 13,
    },
    'fund_hist_sina': {
        'display_name': '基金历史行情-新浪',
        'description': '新浪财经-基金行情日频率数据，包含开盘、收盘、最高、最低、成交量等字段',
        'route': '/funds/collections/fund_hist_sina',
        'order': 14,
    },
    'fund_open_fund_daily_em': {
        'display_name': '开放式基金实时行情-东方财富',
        'description': '东方财富网-天天基金网-基金数据，每个交易日 16:00-23:00 更新当日最新开放式基金净值数据',
        'route': '/funds/collections/fund_open_fund_daily_em',
        'order': 15,
    },
    'fund_open_fund_info_em': {
        'display_name': '开放式基金历史行情-东方财富',
        'description': '东方财富网-天天基金网-基金历史数据，支持7个指标：单位净值走势、累计净值走势、累计收益率走势、同类排名走势、同类排名百分比、分红送配详情、拆分详情',
        'route': '/funds/collections/fund_open_fund_info_em',
        'order': 16,
    },
    'fund_money_fund_daily_em': {
        'display_name': '货币型基金实时行情-东方财富',
        'description': '东方财富网-天天基金网-货币型基金收益，每个交易日 16:00-23:00 更新当日最新数据',
        'route': '/funds/collections/fund_money_fund_daily_em',
        'order': 17,
    },
    'fund_money_fund_info_em': {
        'display_name': '货币型基金历史行情-东方财富',
        'description': '东方财富网-天天基金网-货币型基金历史净值数据',
        'route': '/funds/collections/fund_money_fund_info_em',
        'order': 18,
    },
    'fund_etf_fund_daily_em': {
        'display_name': '场内交易基金实时行情-东方财富',
        'description': '东方财富网-天天基金网-场内交易基金实时数据，每个交易日 16:00-23:00 更新',
        'route': '/funds/collections/fund_etf_fund_daily_em',
        'order': 23,
    },
    'fund_hk_hist_em': {
        'display_name': '香港基金-历史数据',
        'description': '东方财富网-天天基金网-香港基金-历史净值明细和分红送配详情',
        'route': '/funds/collections/fund_hk_hist_em',
        'order': 24,
    },
    'fund_etf_fund_info_em': {
        'display_name': '场内交易基金-历史行情',
        'description': '东方财富网-天天基金网-场内交易基金-历史净值数据',
        'route': '/funds/collections/fund_etf_fund_info_em',
        'order': 25,
    },
    'fund_etf_dividend_sina': {
        'display_name': '基金累计分红-新浪',
        'description': '新浪财经-ETF基金累计分红数据，包含除权除息日、累计分红金额',
        'route': '/funds/collections/fund_etf_dividend_sina',
        'order': 26,
    },
    'fund_fh_em': {
        'display_name': '基金分红-东财',
        'description': '东方财富网-天天基金网-基金数据-分红送配-基金分红，包含权益登记日、除息日期、分红金额等',
        'route': '/funds/collections/fund_fh_em',
        'order': 27,
    },
    'fund_cf_em': {
        'display_name': '基金拆分-东方财富',
        'description': '东方财富网-天天基金网-基金数据-分红送配-基金拆分，包含拆分折算日、拆分类型、拆分折算比例等',
        'route': '/funds/collections/fund_cf_em',
        'order': 28,
    },
    'fund_fh_rank_em': {
        'display_name': '基金分红排行-东方财富',
        'description': '东方财富网-天天基金网-基金数据-分红送配-基金分红排行，包含累计分红、累计次数、成立日期等',
        'route': '/funds/collections/fund_fh_rank_em',
        'order': 29,
    },
    'fund_open_fund_rank_em': {
        'display_name': '开放式基金排行-东方财富',
        'description': '东方财富网-数据中心-开放式基金排行，支持按类型筛选(全部/股票型/混合型/债券型/指数型/QDII/FOF)',
        'route': '/funds/collections/fund_open_fund_rank_em',
        'order': 30,
    },
    'fund_exchange_rank_em': {
        'display_name': '场内交易基金排行-东财',
        'description': '东方财富网-数据中心-场内交易基金排行榜，每个交易日17点后更新',
        'route': '/funds/collections/fund_exchange_rank_em',
        'order': 31,
    },
    'fund_money_rank_em': {
        'display_name': '货币型基金排行-东财',
        'description': '东方财富网-数据中心-货币型基金排行，每个交易日17点后更新',
        'route': '/funds/collections/fund_money_rank_em',
        'order': 32,
    },
    'fund_hk_rank_em': {
        'display_name': '香港基金排行-东财',
        'description': '东方财富网-数据中心-基金排行-香港基金排行',
        'route': '/funds/collections/fund_hk_rank_em',
        'order': 34,
    },
    'fund_individual_achievement_xq': {
        'display_name': '基金业绩-雪球',
        'description': '雪球基金-基金详情-基金业绩-详情（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_individual_achievement_xq',
        'order': 35,
    },
    'fund_value_estimation_em': {
        'display_name': '净值估算-东财',
        'description': '东方财富网-数据中心-净值估算（支持按基金类型过滤）',
        'route': '/funds/collections/fund_value_estimation_em',
        'order': 36,
    },
    'fund_individual_analysis_xq': {
        'display_name': '基金数据分析-雪球',
        'description': '雪球基金-基金详情-数据分析（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_individual_analysis_xq',
        'order': 37,
    },
    'fund_individual_profit_probability_xq': {
        'display_name': '基金盈利概率-雪球',
        'description': '雪球基金-基金详情-盈利概率（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_individual_profit_probability_xq',
        'order': 38,
    },
    'fund_individual_detail_hold_xq': {
        'display_name': '基金持仓资产比例-雪球',
        'description': '雪球基金-基金详情-持仓资产比例（需要基金代码和日期，支持单个/批量更新）',
        'route': '/funds/collections/fund_individual_detail_hold_xq',
        'order': 39,
    },
    'fund_overview_em': {
        'display_name': '基金基本概况-东财',
        'description': '东方财富网-数据中心-基金基本概况（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_overview_em',
        'order': 40,
    },
    'fund_fee_em': {
        'display_name': '基金交易费率-东财',
        'description': '东方财富网-数据中心-基金交易费率（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_fee_em',
        'order': 41,
    },
    'fund_individual_detail_info_xq': {
        'display_name': '基金交易规则-雪球',
        'description': '雪球基金-基金详情-交易规则（需要基金代码，支持单个/批量更新）',
        'route': '/funds/collections/fund_individual_detail_info_xq',
        'order': 42,
    },
    'fund_portfolio_hold_em': {
        'display_name': '基金持仓-东财',
        'description': '东方财富网-数据中心-基金持仓（需要基金代码和日期，支持单个/批量更新）',
        'route': '/funds/collections/fund_portfolio_hold_em',
        'order': 43,
    },
    'fund_portfolio_bond_hold_em': {
        'display_name': '债券持仓-东财',
        'description': '东方财富网-数据中心-债券持仓（需要基金代码和日期，支持单个/批量更新）',
        'route': '/funds/collections/fund_portfolio_bond_hold_em',
        'order': 44,
    },
    'fund_portfolio_industry_allocation_em': {
        'display_name': '行业配置-东财',
        'description': '东方财富网-数据中心-行业配置（需要基金代码和日期，支持单个/批量更新）',
        'route': '/funds/collections/fund_portfolio_industry_allocation_em',
        'order': 45,
    },
    'fund_portfolio_change_em': {
        'display_name': '重大变动-东财',
        'description': '东方财富网-数据中心-重大变动（需要基金代码和年份，支持单个/批量更新）',
        'route': '/funds/collections/fund_portfolio_change_em',
        'order': 46,
    },
    'fund_rating_all_em': {
        'display_name': '基金评级总汇-东财',
        'description': '东方财富网-基金评级-基金评级总汇（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_rating_all_em',
        'order': 47,
    },
    'fund_rating_sh_em': {
        'display_name': '上海证券评级-东财',
        'description': '东方财富网-基金评级-上海证券评级（需要日期参数YYYYMMDD）',
        'route': '/funds/collections/fund_rating_sh_em',
        'order': 48,
    },
    'fund_rating_zs_em': {
        'display_name': '招商证券评级-东财',
        'description': '东方财富网-基金评级-招商证券评级（需要日期参数YYYYMMDD）',
        'route': '/funds/collections/fund_rating_zs_em',
        'order': 49,
    },
    'fund_rating_ja_em': {
        'display_name': '济安金信评级-东财',
        'description': '东方财富网-基金评级-济安金信评级（需要日期参数YYYYMMDD）',
        'route': '/funds/collections/fund_rating_ja_em',
        'order': 50,
    },
    'fund_manager_em': {
        'display_name': '基金经理-东财',
        'description': '东方财富网-基金数据-基金经理大全（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_manager_em',
        'order': 51,
    },
    'fund_new_found_em': {
        'display_name': '新发基金-东财',
        'description': '东方财富网-基金数据-新发基金（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_new_found_em',
        'order': 52,
    },
    'fund_scale_open_sina': {
        'display_name': '开放式基金规模-新浪',
        'description': '新浪财经-基金数据-开放式基金规模（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_scale_open_sina',
        'order': 53,
    },
    'fund_scale_close_sina': {
        'display_name': '封闭式基金规模-新浪',
        'description': '新浪财经-基金数据-封闭式基金规模（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_scale_close_sina',
        'order': 54,
    },
    'fund_aum_em': {
        'display_name': '基金规模详情-东财',
        'description': '东方财富网-基金数据-基金公司管理规模（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_aum_em',
        'order': 56,
    },
    'fund_aum_trend_em': {
        'display_name': '基金规模走势-东财',
        'description': '东方财富网-基金数据-基金规模走势（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_aum_trend_em',
        'order': 57,
    },
    'fund_aum_hist_em': {
        'display_name': '基金公司历年管理规模-东财',
        'description': '东方财富网-基金数据-基金公司历年管理规模（无需参数，支持更新所有）',
        'route': '/funds/collections/fund_aum_hist_em',
        'order': 58,
    },
    'reits_realtime_em': {
        'display_name': 'REITs实时行情-东财',
        'description': '东方财富网-行情中心-REITs-沪深 REITs-实时行情（无需参数，支持更新所有）',
        'route': '/funds/collections/reits_realtime_em',
        'order': 59,
    },
    'reits_hist_em': {
        'display_name': 'REITs历史行情-东财',
        'description': '东方财富网-行情中心-REITs-沪深 REITs-历史行情（需code参数，不传则更新所有）',
        'route': '/funds/collections/reits_hist_em',
        'order': 60,
    },
    'fund_report_stock_cninfo': {
        'display_name': '基金重仓股-巨潮',
        'description': '巨潮资讯-基金数据-基金重仓股（需date参数，YYYYMMDD格式，默认最近季度）',
        'route': '/funds/collections/fund_report_stock_cninfo',
        'order': 61,
    },
    'fund_report_industry_allocation_cninfo': {
        'display_name': '基金行业配置-巨潮',
        'description': '巨潮资讯-基金数据-基金行业配置（需date参数，YYYYMMDD格式，默认最近季度）',
        'route': '/funds/collections/fund_report_industry_allocation_cninfo',
        'order': 62,
    },
    'fund_report_asset_allocation_cninfo': {
        'display_name': '基金资产配置-巨潮',
        'description': '巨潮资讯-基金数据-基金资产配置（需date参数，YYYYMMDD格式，默认最近季度）',
        'route': '/funds/collections/fund_report_asset_allocation_cninfo',
        'order': 63,
    },
    'fund_scale_change_em': {
        'display_name': '规模变动-东财',
        'description': '东方财富网-基金数据-规模变动（需code参数）',
        'route': '/funds/collections/fund_scale_change_em',
        'order': 64,
    },
    'fund_hold_structure_em': {
        'display_name': '持有人结构-东财',
        'description': '东方财富网-基金数据-持有人结构（需code参数）',
        'route': '/funds/collections/fund_hold_structure_em',
        'order': 65,
    },
    'fund_stock_position_lg': {
        'display_name': '股票型基金仓位-乐咕乐股',
        'description': '乐咕乐股-基金数据-股票型基金仓位（无参数）',
        'route': '/funds/collections/fund_stock_position_lg',
        'order': 66,
    },
    'fund_balance_position_lg': {
        'display_name': '平衡混合型基金仓位-乐咕乐股',
        'description': '乐咕乐股-基金数据-平衡混合型基金仓位（无参数）',
        'route': '/funds/collections/fund_balance_position_lg',
        'order': 67,
    },
    'fund_linghuo_position_lg': {
        'display_name': '灵活配置型基金仓位-乐咕乐股',
        'description': '乐咕乐股-基金数据-灵活配置型基金仓位（无参数）',
        'route': '/funds/collections/fund_linghuo_position_lg',
        'order': 68,
    },
    'fund_announcement_dividend_em': {
        'display_name': '基金公告分红配送-东财',
        'description': '东方财富网-基金数据-公告-分红配送（无参数）',
        'route': '/funds/collections/fund_announcement_dividend_em',
        'order': 69,
    },
    'fund_announcement_report_em': {
        'display_name': '基金公告定期报告-东财',
        'description': '东方财富网-基金数据-公告-定期报告（无参数）',
        'route': '/funds/collections/fund_announcement_report_em',
        'order': 70,
    },
    'fund_announcement_personnel_em': {
        'display_name': '基金公告人事调整-东财',
        'description': '东方财富网-基金数据-公告-人事调整（无参数）',
        'route': '/funds/collections/fund_announcement_personnel_em',
        'order': 71,
    },
}