"""
生成的集合注册代码
需要手动添加到 app/routers/stocks.py 的 collections 列表中
"""

# 将以下代码添加到 collections 列表中
collections = [
{
    "name": "news_report_time_baidu",
    "display_name": "财报发行",
    "description": "财报发行数据",
    "route": "/stocks/collections/news_report_time_baidu",
    "fields": [],
},
{
    "name": "news_trade_notify_dividend_baidu",
    "display_name": "分红派息",
    "description": "分红派息数据",
    "route": "/stocks/collections/news_trade_notify_dividend_baidu",
    "fields": [],
},
{
    "name": "news_trade_notify_suspend_baidu",
    "display_name": "停复牌",
    "description": "停复牌数据",
    "route": "/stocks/collections/news_trade_notify_suspend_baidu",
    "fields": [],
},
{
    "name": "stock_a_all_pb",
    "display_name": "A 股等权重与中位数市净率",
    "description": "A 股等权重与中位数市净率数据",
    "route": "/stocks/collections/stock_a_all_pb",
    "fields": [],
},
{
    "name": "stock_a_below_net_asset_statistics",
    "display_name": "破净股统计",
    "description": "破净股统计数据",
    "route": "/stocks/collections/stock_a_below_net_asset_statistics",
    "fields": [],
},
{
    "name": "stock_a_congestion_lg",
    "display_name": "大盘拥挤度",
    "description": "大盘拥挤度数据",
    "route": "/stocks/collections/stock_a_congestion_lg",
    "fields": [],
},
{
    "name": "stock_a_gxl_lg",
    "display_name": "A 股股息率",
    "description": "A 股股息率数据",
    "route": "/stocks/collections/stock_a_gxl_lg",
    "fields": [],
},
{
    "name": "stock_a_high_low_statistics",
    "display_name": "创新高和新低的股票数量",
    "description": "创新高和新低的股票数量数据",
    "route": "/stocks/collections/stock_a_high_low_statistics",
    "fields": [],
},
{
    "name": "stock_a_ttm_lyr",
    "display_name": "A 股等权重与中位数市盈率",
    "description": "A 股等权重与中位数市盈率数据",
    "route": "/stocks/collections/stock_a_ttm_lyr",
    "fields": [],
},
{
    "name": "stock_account_statistics_em",
    "display_name": "股票账户统计月度",
    "description": "股票账户统计月度数据",
    "route": "/stocks/collections/stock_account_statistics_em",
    "fields": [],
},
{
    "name": "stock_add_stock",
    "display_name": "股票增发",
    "description": "股票增发数据",
    "route": "/stocks/collections/stock_add_stock",
    "fields": [],
},
{
    "name": "stock_allotment_cninfo",
    "display_name": "配股实施方案-巨潮资讯",
    "description": "配股实施方案-巨潮资讯数据",
    "route": "/stocks/collections/stock_allotment_cninfo",
    "fields": [],
},
{
    "name": "stock_analyst_detail_em",
    "display_name": "分析师详情",
    "description": "分析师详情数据",
    "route": "/stocks/collections/stock_analyst_detail_em",
    "fields": [],
},
{
    "name": "stock_analyst_rank_em",
    "display_name": "分析师指数排行",
    "description": "分析师指数排行数据",
    "route": "/stocks/collections/stock_analyst_rank_em",
    "fields": [],
},
{
    "name": "stock_balance_sheet_by_yearly_em",
    "display_name": "资产负债表-按年度",
    "description": "资产负债表-按年度数据",
    "route": "/stocks/collections/stock_balance_sheet_by_yearly_em",
    "fields": [],
},
{
    "name": "stock_bid_ask_em",
    "display_name": "行情报价",
    "description": "行情报价数据",
    "route": "/stocks/collections/stock_bid_ask_em",
    "fields": [],
},
{
    "name": "stock_bj_a_spot_em",
    "display_name": "京 A 股",
    "description": "京 A 股数据",
    "route": "/stocks/collections/stock_bj_a_spot_em",
    "fields": [],
},
{
    "name": "stock_board_change_em",
    "display_name": "板块异动详情",
    "description": "板块异动详情数据",
    "route": "/stocks/collections/stock_board_change_em",
    "fields": [],
},
{
    "name": "stock_board_concept_cons_em",
    "display_name": "东方财富-成份股",
    "description": "东方财富-成份股数据",
    "route": "/stocks/collections/stock_board_concept_cons_em",
    "fields": [],
},
{
    "name": "stock_board_concept_hist_em",
    "display_name": "东方财富-指数",
    "description": "东方财富-指数数据",
    "route": "/stocks/collections/stock_board_concept_hist_em",
    "fields": [],
},
{
    "name": "stock_board_concept_hist_min_em",
    "display_name": "东方财富-指数-分时",
    "description": "东方财富-指数-分时数据",
    "route": "/stocks/collections/stock_board_concept_hist_min_em",
    "fields": [],
},
{
    "name": "stock_board_concept_index_ths",
    "display_name": "同花顺-概念板块指数",
    "description": "同花顺-概念板块指数数据",
    "route": "/stocks/collections/stock_board_concept_index_ths",
    "fields": [],
},
{
    "name": "stock_board_concept_info_ths",
    "display_name": "同花顺-概念板块简介",
    "description": "同花顺-概念板块简介数据",
    "route": "/stocks/collections/stock_board_concept_info_ths",
    "fields": [],
},
{
    "name": "stock_board_concept_name_em",
    "display_name": "东方财富-概念板块",
    "description": "东方财富-概念板块数据",
    "route": "/stocks/collections/stock_board_concept_name_em",
    "fields": [],
},
{
    "name": "stock_board_concept_spot_em",
    "display_name": "东方财富-概念板块-实时行情",
    "description": "东方财富-概念板块-实时行情数据",
    "route": "/stocks/collections/stock_board_concept_spot_em",
    "fields": [],
},
{
    "name": "stock_board_industry_cons_em",
    "display_name": "东方财富-成份股",
    "description": "东方财富-成份股数据",
    "route": "/stocks/collections/stock_board_industry_cons_em",
    "fields": [],
},
{
    "name": "stock_board_industry_hist_em",
    "display_name": "东方财富-指数-日频",
    "description": "东方财富-指数-日频数据",
    "route": "/stocks/collections/stock_board_industry_hist_em",
    "fields": [],
},
{
    "name": "stock_board_industry_hist_min_em",
    "display_name": "东方财富-指数-分时",
    "description": "东方财富-指数-分时数据",
    "route": "/stocks/collections/stock_board_industry_hist_min_em",
    "fields": [],
},
{
    "name": "stock_board_industry_index_ths",
    "display_name": "同花顺-指数",
    "description": "同花顺-指数数据",
    "route": "/stocks/collections/stock_board_industry_index_ths",
    "fields": [],
},
{
    "name": "stock_board_industry_spot_em",
    "display_name": "东方财富-行业板块-实时行情",
    "description": "东方财富-行业板块-实时行情数据",
    "route": "/stocks/collections/stock_board_industry_spot_em",
    "fields": [],
},
{
    "name": "stock_board_industry_summary_ths",
    "display_name": "同花顺-同花顺行业一览表",
    "description": "同花顺-同花顺行业一览表数据",
    "route": "/stocks/collections/stock_board_industry_summary_ths",
    "fields": [],
},
{
    "name": "stock_buffett_index_lg",
    "display_name": "巴菲特指标",
    "description": "巴菲特指标数据",
    "route": "/stocks/collections/stock_buffett_index_lg",
    "fields": [],
},
{
    "name": "stock_cg_equity_mortgage_cninfo",
    "display_name": "股权质押",
    "description": "股权质押数据",
    "route": "/stocks/collections/stock_cg_equity_mortgage_cninfo",
    "fields": [],
},
{
    "name": "stock_cg_guarantee_cninfo",
    "display_name": "对外担保",
    "description": "对外担保数据",
    "route": "/stocks/collections/stock_cg_guarantee_cninfo",
    "fields": [],
},
{
    "name": "stock_cg_lawsuit_cninfo",
    "display_name": "公司诉讼",
    "description": "公司诉讼数据",
    "route": "/stocks/collections/stock_cg_lawsuit_cninfo",
    "fields": [],
},
{
    "name": "stock_changes_em",
    "display_name": "盘口异动",
    "description": "盘口异动数据",
    "route": "/stocks/collections/stock_changes_em",
    "fields": [],
},
{
    "name": "stock_circulate_stock_holder",
    "display_name": "流通股东",
    "description": "流通股东数据",
    "route": "/stocks/collections/stock_circulate_stock_holder",
    "fields": [],
},
{
    "name": "stock_comment_detail_scrd_desire_daily_em",
    "display_name": "日度市场参与意愿",
    "description": "日度市场参与意愿数据",
    "route": "/stocks/collections/stock_comment_detail_scrd_desire_daily_em",
    "fields": [],
},
{
    "name": "stock_comment_detail_scrd_desire_em",
    "display_name": "市场参与意愿",
    "description": "市场参与意愿数据",
    "route": "/stocks/collections/stock_comment_detail_scrd_desire_em",
    "fields": [],
},
{
    "name": "stock_comment_detail_scrd_focus_em",
    "display_name": "用户关注指数",
    "description": "用户关注指数数据",
    "route": "/stocks/collections/stock_comment_detail_scrd_focus_em",
    "fields": [],
},
{
    "name": "stock_comment_detail_zhpj_lspf_em",
    "display_name": "历史评分",
    "description": "历史评分数据",
    "route": "/stocks/collections/stock_comment_detail_zhpj_lspf_em",
    "fields": [],
},
{
    "name": "stock_comment_detail_zlkp_jgcyd_em",
    "display_name": "机构参与度",
    "description": "机构参与度数据",
    "route": "/stocks/collections/stock_comment_detail_zlkp_jgcyd_em",
    "fields": [],
},
{
    "name": "stock_comment_em",
    "display_name": "千股千评",
    "description": "千股千评数据",
    "route": "/stocks/collections/stock_comment_em",
    "fields": [],
},
{
    "name": "stock_concept_cons_futu",
    "display_name": "富途牛牛-美股概念-成分股",
    "description": "富途牛牛-美股概念-成分股数据",
    "route": "/stocks/collections/stock_concept_cons_futu",
    "fields": [],
},
{
    "name": "stock_cy_a_spot_em",
    "display_name": "创业板",
    "description": "创业板数据",
    "route": "/stocks/collections/stock_cy_a_spot_em",
    "fields": [],
},
{
    "name": "stock_dividend_cninfo",
    "display_name": "历史分红",
    "description": "历史分红数据",
    "route": "/stocks/collections/stock_dividend_cninfo",
    "fields": [],
},
{
    "name": "stock_dxsyl_em",
    "display_name": "打新收益率",
    "description": "打新收益率数据",
    "route": "/stocks/collections/stock_dxsyl_em",
    "fields": [],
},
{
    "name": "stock_dzjy_hygtj",
    "display_name": "活跃 A 股统计",
    "description": "活跃 A 股统计数据",
    "route": "/stocks/collections/stock_dzjy_hygtj",
    "fields": [],
},
{
    "name": "stock_dzjy_hyyybtj",
    "display_name": "活跃营业部统计",
    "description": "活跃营业部统计数据",
    "route": "/stocks/collections/stock_dzjy_hyyybtj",
    "fields": [],
},
{
    "name": "stock_dzjy_yybph",
    "display_name": "营业部排行",
    "description": "营业部排行数据",
    "route": "/stocks/collections/stock_dzjy_yybph",
    "fields": [],
},
{
    "name": "stock_ebs_lg",
    "display_name": "股债利差",
    "description": "股债利差数据",
    "route": "/stocks/collections/stock_ebs_lg",
    "fields": [],
},
{
    "name": "stock_esg_hz_sina",
    "display_name": "华证指数",
    "description": "华证指数数据",
    "route": "/stocks/collections/stock_esg_hz_sina",
    "fields": [],
},
{
    "name": "stock_esg_msci_sina",
    "display_name": "MSCI",
    "description": "MSCI数据",
    "route": "/stocks/collections/stock_esg_msci_sina",
    "fields": [],
},
{
    "name": "stock_esg_rate_sina",
    "display_name": "ESG 评级数据",
    "description": "ESG 评级数据数据",
    "route": "/stocks/collections/stock_esg_rate_sina",
    "fields": [],
},
{
    "name": "stock_esg_rft_sina",
    "display_name": "路孚特",
    "description": "路孚特数据",
    "route": "/stocks/collections/stock_esg_rft_sina",
    "fields": [],
},
{
    "name": "stock_esg_zd_sina",
    "display_name": "秩鼎",
    "description": "秩鼎数据",
    "route": "/stocks/collections/stock_esg_zd_sina",
    "fields": [],
},
{
    "name": "stock_fhps_detail_em",
    "display_name": "分红配送详情-东财",
    "description": "分红配送详情-东财数据",
    "route": "/stocks/collections/stock_fhps_detail_em",
    "fields": [],
},
{
    "name": "stock_fhps_em",
    "display_name": "分红配送-东财",
    "description": "分红配送-东财数据",
    "route": "/stocks/collections/stock_fhps_em",
    "fields": [],
},
{
    "name": "stock_fund_stock_holder",
    "display_name": "基金持股",
    "description": "基金持股数据",
    "route": "/stocks/collections/stock_fund_stock_holder",
    "fields": [],
},
{
    "name": "stock_gdfx_free_holding_detail_em",
    "display_name": "股东持股明细-十大流通股东",
    "description": "股东持股明细-十大流通股东数据",
    "route": "/stocks/collections/stock_gdfx_free_holding_detail_em",
    "fields": [],
},
{
    "name": "stock_gdfx_free_holding_statistics_em",
    "display_name": "股东持股统计-十大流通股东",
    "description": "股东持股统计-十大流通股东数据",
    "route": "/stocks/collections/stock_gdfx_free_holding_statistics_em",
    "fields": [],
},
{
    "name": "stock_gdfx_free_holding_teamwork_em",
    "display_name": "股东协同-十大流通股东",
    "description": "股东协同-十大流通股东数据",
    "route": "/stocks/collections/stock_gdfx_free_holding_teamwork_em",
    "fields": [],
},
{
    "name": "stock_gdfx_holding_detail_em",
    "display_name": "股东持股明细-十大股东",
    "description": "股东持股明细-十大股东数据",
    "route": "/stocks/collections/stock_gdfx_holding_detail_em",
    "fields": [],
},
{
    "name": "stock_gdfx_holding_statistics_em",
    "display_name": "股东持股统计-十大股东",
    "description": "股东持股统计-十大股东数据",
    "route": "/stocks/collections/stock_gdfx_holding_statistics_em",
    "fields": [],
},
{
    "name": "stock_gdfx_holding_teamwork_em",
    "display_name": "股东协同-十大股东",
    "description": "股东协同-十大股东数据",
    "route": "/stocks/collections/stock_gdfx_holding_teamwork_em",
    "fields": [],
},
{
    "name": "stock_ggcg_em",
    "display_name": "股东增减持",
    "description": "股东增减持数据",
    "route": "/stocks/collections/stock_ggcg_em",
    "fields": [],
},
{
    "name": "stock_gpzy_distribute_statistics_bank_em",
    "display_name": "质押机构分布统计-银行",
    "description": "质押机构分布统计-银行数据",
    "route": "/stocks/collections/stock_gpzy_distribute_statistics_bank_em",
    "fields": [],
},
{
    "name": "stock_gpzy_distribute_statistics_company_em",
    "display_name": "质押机构分布统计-证券公司",
    "description": "质押机构分布统计-证券公司数据",
    "route": "/stocks/collections/stock_gpzy_distribute_statistics_company_em",
    "fields": [],
},
{
    "name": "stock_gpzy_industry_data_em",
    "display_name": "上市公司质押比例",
    "description": "上市公司质押比例数据",
    "route": "/stocks/collections/stock_gpzy_industry_data_em",
    "fields": [],
},
{
    "name": "stock_gpzy_pledge_ratio_detail_em",
    "display_name": "重要股东股权质押明细",
    "description": "重要股东股权质押明细数据",
    "route": "/stocks/collections/stock_gpzy_pledge_ratio_detail_em",
    "fields": [],
},
{
    "name": "stock_gpzy_pledge_ratio_em",
    "display_name": "上市公司质押比例",
    "description": "上市公司质押比例数据",
    "route": "/stocks/collections/stock_gpzy_pledge_ratio_em",
    "fields": [],
},
{
    "name": "stock_gsrl_gsdt_em",
    "display_name": "公司动态",
    "description": "公司动态数据",
    "route": "/stocks/collections/stock_gsrl_gsdt_em",
    "fields": [],
},
{
    "name": "stock_history_dividend_detail",
    "display_name": "分红配股",
    "description": "分红配股数据",
    "route": "/stocks/collections/stock_history_dividend_detail",
    "fields": [],
},
{
    "name": "stock_hk_company_profile_em",
    "display_name": "公司资料",
    "description": "公司资料数据",
    "route": "/stocks/collections/stock_hk_company_profile_em",
    "fields": [],
},
{
    "name": "stock_hk_daily",
    "display_name": "历史行情数据-新浪",
    "description": "历史行情数据-新浪数据",
    "route": "/stocks/collections/stock_hk_daily",
    "fields": [],
},
{
    "name": "stock_hk_dividend_payout_em",
    "display_name": "分红派息",
    "description": "分红派息数据",
    "route": "/stocks/collections/stock_hk_dividend_payout_em",
    "fields": [],
},
{
    "name": "stock_hk_famous_spot_em",
    "display_name": "知名港股",
    "description": "知名港股数据",
    "route": "/stocks/collections/stock_hk_famous_spot_em",
    "fields": [],
},
{
    "name": "stock_hk_financial_indicator_em",
    "display_name": "财务指标",
    "description": "财务指标数据",
    "route": "/stocks/collections/stock_hk_financial_indicator_em",
    "fields": [],
},
{
    "name": "stock_hk_growth_comparison_em",
    "display_name": "成长性对比",
    "description": "成长性对比数据",
    "route": "/stocks/collections/stock_hk_growth_comparison_em",
    "fields": [],
},
{
    "name": "stock_hk_gxl_lg",
    "display_name": "恒生指数股息率",
    "description": "恒生指数股息率数据",
    "route": "/stocks/collections/stock_hk_gxl_lg",
    "fields": [],
},
{
    "name": "stock_hk_hist",
    "display_name": "历史行情数据-东财",
    "description": "历史行情数据-东财数据",
    "route": "/stocks/collections/stock_hk_hist",
    "fields": [],
},
{
    "name": "stock_hk_hist_min_em",
    "display_name": "分时数据-东财",
    "description": "分时数据-东财数据",
    "route": "/stocks/collections/stock_hk_hist_min_em",
    "fields": [],
},
{
    "name": "stock_hk_hot_rank_detail_em",
    "display_name": "港股",
    "description": "港股数据",
    "route": "/stocks/collections/stock_hk_hot_rank_detail_em",
    "fields": [],
},
{
    "name": "stock_hk_hot_rank_detail_realtime_em",
    "display_name": "港股",
    "description": "港股数据",
    "route": "/stocks/collections/stock_hk_hot_rank_detail_realtime_em",
    "fields": [],
},
{
    "name": "stock_hk_hot_rank_em",
    "display_name": "人气榜-港股",
    "description": "人气榜-港股数据",
    "route": "/stocks/collections/stock_hk_hot_rank_em",
    "fields": [],
},
{
    "name": "stock_hk_hot_rank_latest_em",
    "display_name": "港股",
    "description": "港股数据",
    "route": "/stocks/collections/stock_hk_hot_rank_latest_em",
    "fields": [],
},
{
    "name": "stock_hk_indicator_eniu",
    "display_name": "港股个股指标",
    "description": "港股个股指标数据",
    "route": "/stocks/collections/stock_hk_indicator_eniu",
    "fields": [],
},
{
    "name": "stock_hk_main_board_spot_em",
    "display_name": "港股主板实时行情数据-东财",
    "description": "港股主板实时行情数据-东财数据",
    "route": "/stocks/collections/stock_hk_main_board_spot_em",
    "fields": [],
},
{
    "name": "stock_hk_profit_forecast_et",
    "display_name": "港股盈利预测-经济通",
    "description": "港股盈利预测-经济通数据",
    "route": "/stocks/collections/stock_hk_profit_forecast_et",
    "fields": [],
},
{
    "name": "stock_hk_scale_comparison_em",
    "display_name": "规模对比",
    "description": "规模对比数据",
    "route": "/stocks/collections/stock_hk_scale_comparison_em",
    "fields": [],
},
{
    "name": "stock_hk_security_profile_em",
    "display_name": "证券资料",
    "description": "证券资料数据",
    "route": "/stocks/collections/stock_hk_security_profile_em",
    "fields": [],
},
{
    "name": "stock_hk_spot",
    "display_name": "实时行情数据-新浪",
    "description": "实时行情数据-新浪数据",
    "route": "/stocks/collections/stock_hk_spot",
    "fields": [],
},
{
    "name": "stock_hk_spot_em",
    "display_name": "实时行情数据-东财",
    "description": "实时行情数据-东财数据",
    "route": "/stocks/collections/stock_hk_spot_em",
    "fields": [],
},
{
    "name": "stock_hk_valuation_baidu",
    "display_name": "港股估值指标",
    "description": "港股估值指标数据",
    "route": "/stocks/collections/stock_hk_valuation_baidu",
    "fields": [],
},
{
    "name": "stock_hk_valuation_comparison_em",
    "display_name": "估值对比",
    "description": "估值对比数据",
    "route": "/stocks/collections/stock_hk_valuation_comparison_em",
    "fields": [],
},
{
    "name": "stock_hold_change_cninfo",
    "display_name": "股本变动",
    "description": "股本变动数据",
    "route": "/stocks/collections/stock_hold_change_cninfo",
    "fields": [],
},
{
    "name": "stock_hold_control_cninfo",
    "display_name": "实际控制人持股变动",
    "description": "实际控制人持股变动数据",
    "route": "/stocks/collections/stock_hold_control_cninfo",
    "fields": [],
},
{
    "name": "stock_hold_management_detail_cninfo",
    "display_name": "高管持股变动明细",
    "description": "高管持股变动明细数据",
    "route": "/stocks/collections/stock_hold_management_detail_cninfo",
    "fields": [],
},
{
    "name": "stock_hold_management_detail_em",
    "display_name": "董监高及相关人员持股变动明细",
    "description": "董监高及相关人员持股变动明细数据",
    "route": "/stocks/collections/stock_hold_management_detail_em",
    "fields": [],
},
{
    "name": "stock_hold_management_person_em",
    "display_name": "人员增减持股变动明细",
    "description": "人员增减持股变动明细数据",
    "route": "/stocks/collections/stock_hold_management_person_em",
    "fields": [],
},
{
    "name": "stock_hold_num_cninfo",
    "display_name": "股东人数及持股集中度",
    "description": "股东人数及持股集中度数据",
    "route": "/stocks/collections/stock_hold_num_cninfo",
    "fields": [],
},
{
    "name": "stock_hot_deal_xq",
    "display_name": "交易排行榜",
    "description": "交易排行榜数据",
    "route": "/stocks/collections/stock_hot_deal_xq",
    "fields": [],
},
{
    "name": "stock_hot_follow_xq",
    "display_name": "关注排行榜",
    "description": "关注排行榜数据",
    "route": "/stocks/collections/stock_hot_follow_xq",
    "fields": [],
},
{
    "name": "stock_hot_keyword_em",
    "display_name": "热门关键词",
    "description": "热门关键词数据",
    "route": "/stocks/collections/stock_hot_keyword_em",
    "fields": [],
},
{
    "name": "stock_hot_rank_detail_em",
    "display_name": "A股",
    "description": "A股数据",
    "route": "/stocks/collections/stock_hot_rank_detail_em",
    "fields": [],
},
{
    "name": "stock_hot_rank_detail_realtime_em",
    "display_name": "A股",
    "description": "A股数据",
    "route": "/stocks/collections/stock_hot_rank_detail_realtime_em",
    "fields": [],
},
{
    "name": "stock_hot_rank_em",
    "display_name": "人气榜-A股",
    "description": "人气榜-A股数据",
    "route": "/stocks/collections/stock_hot_rank_em",
    "fields": [],
},
{
    "name": "stock_hot_rank_latest_em",
    "display_name": "A股",
    "description": "A股数据",
    "route": "/stocks/collections/stock_hot_rank_latest_em",
    "fields": [],
},
{
    "name": "stock_hot_rank_relate_em",
    "display_name": "相关股票",
    "description": "相关股票数据",
    "route": "/stocks/collections/stock_hot_rank_relate_em",
    "fields": [],
},
{
    "name": "stock_hot_search_baidu",
    "display_name": "热搜股票",
    "description": "热搜股票数据",
    "route": "/stocks/collections/stock_hot_search_baidu",
    "fields": [],
},
{
    "name": "stock_hot_tweet_xq",
    "display_name": "讨论排行榜",
    "description": "讨论排行榜数据",
    "route": "/stocks/collections/stock_hot_tweet_xq",
    "fields": [],
},
{
    "name": "stock_hot_up_em",
    "display_name": "飙升榜-A股",
    "description": "飙升榜-A股数据",
    "route": "/stocks/collections/stock_hot_up_em",
    "fields": [],
},
{
    "name": "stock_hsgt_fund_flow_summary_em",
    "display_name": "沪深港通资金流向",
    "description": "沪深港通资金流向数据",
    "route": "/stocks/collections/stock_hsgt_fund_flow_summary_em",
    "fields": [],
},
{
    "name": "stock_index_pb_lg",
    "display_name": "指数市净率",
    "description": "指数市净率数据",
    "route": "/stocks/collections/stock_index_pb_lg",
    "fields": [],
},
{
    "name": "stock_index_pe_lg",
    "display_name": "指数市盈率",
    "description": "指数市盈率数据",
    "route": "/stocks/collections/stock_index_pe_lg",
    "fields": [],
},
{
    "name": "stock_individual_basic_info_hk_xq",
    "display_name": "个股信息查询-雪球",
    "description": "个股信息查询-雪球数据",
    "route": "/stocks/collections/stock_individual_basic_info_hk_xq",
    "fields": [],
},
{
    "name": "stock_individual_basic_info_us_xq",
    "display_name": "个股信息查询-雪球",
    "description": "个股信息查询-雪球数据",
    "route": "/stocks/collections/stock_individual_basic_info_us_xq",
    "fields": [],
},
{
    "name": "stock_individual_basic_info_xq",
    "display_name": "个股信息查询-雪球",
    "description": "个股信息查询-雪球数据",
    "route": "/stocks/collections/stock_individual_basic_info_xq",
    "fields": [],
},
{
    "name": "stock_individual_info_em",
    "display_name": "个股信息查询-东财",
    "description": "个股信息查询-东财数据",
    "route": "/stocks/collections/stock_individual_info_em",
    "fields": [],
},
{
    "name": "stock_individual_spot_xq",
    "display_name": "实时行情数据-雪球",
    "description": "实时行情数据-雪球数据",
    "route": "/stocks/collections/stock_individual_spot_xq",
    "fields": [],
},
{
    "name": "stock_industry_category_cninfo",
    "display_name": "行业分类数据-巨潮资讯",
    "description": "行业分类数据-巨潮资讯数据",
    "route": "/stocks/collections/stock_industry_category_cninfo",
    "fields": [],
},
{
    "name": "stock_industry_change_cninfo",
    "display_name": "上市公司行业归属的变动情况-巨潮资讯",
    "description": "上市公司行业归属的变动情况-巨潮资讯数据",
    "route": "/stocks/collections/stock_industry_change_cninfo",
    "fields": [],
},
{
    "name": "stock_industry_clf_hist_sw",
    "display_name": "申万个股行业分类变动历史",
    "description": "申万个股行业分类变动历史数据",
    "route": "/stocks/collections/stock_industry_clf_hist_sw",
    "fields": [],
},
{
    "name": "stock_industry_pe_ratio_cninfo",
    "display_name": "行业市盈率",
    "description": "行业市盈率数据",
    "route": "/stocks/collections/stock_industry_pe_ratio_cninfo",
    "fields": [],
},
{
    "name": "stock_info_a_code_name",
    "display_name": "股票列表-A股",
    "description": "股票列表-A股数据",
    "route": "/stocks/collections/stock_info_a_code_name",
    "fields": [],
},
{
    "name": "stock_info_bj_name_code",
    "display_name": "股票列表-北证",
    "description": "股票列表-北证数据",
    "route": "/stocks/collections/stock_info_bj_name_code",
    "fields": [],
},
{
    "name": "stock_info_change_name",
    "display_name": "股票更名",
    "description": "股票更名数据",
    "route": "/stocks/collections/stock_info_change_name",
    "fields": [],
},
{
    "name": "stock_info_sh_delist",
    "display_name": "暂停-终止上市-上证",
    "description": "暂停-终止上市-上证数据",
    "route": "/stocks/collections/stock_info_sh_delist",
    "fields": [],
},
{
    "name": "stock_info_sh_name_code",
    "display_name": "股票列表-上证",
    "description": "股票列表-上证数据",
    "route": "/stocks/collections/stock_info_sh_name_code",
    "fields": [],
},
{
    "name": "stock_info_sz_change_name",
    "display_name": "名称变更-深证",
    "description": "名称变更-深证数据",
    "route": "/stocks/collections/stock_info_sz_change_name",
    "fields": [],
},
{
    "name": "stock_info_sz_delist",
    "display_name": "终止-暂停上市-深证",
    "description": "终止-暂停上市-深证数据",
    "route": "/stocks/collections/stock_info_sz_delist",
    "fields": [],
},
{
    "name": "stock_info_sz_name_code",
    "display_name": "股票列表-深证",
    "description": "股票列表-深证数据",
    "route": "/stocks/collections/stock_info_sz_name_code",
    "fields": [],
},
{
    "name": "stock_inner_trade_xq",
    "display_name": "内部交易",
    "description": "内部交易数据",
    "route": "/stocks/collections/stock_inner_trade_xq",
    "fields": [],
},
{
    "name": "stock_institute_hold",
    "display_name": "机构持股一览表",
    "description": "机构持股一览表数据",
    "route": "/stocks/collections/stock_institute_hold",
    "fields": [],
},
{
    "name": "stock_institute_hold_detail",
    "display_name": "机构持股详情",
    "description": "机构持股详情数据",
    "route": "/stocks/collections/stock_institute_hold_detail",
    "fields": [],
},
{
    "name": "stock_institute_recommend",
    "display_name": "机构推荐池",
    "description": "机构推荐池数据",
    "route": "/stocks/collections/stock_institute_recommend",
    "fields": [],
},
{
    "name": "stock_institute_recommend_detail",
    "display_name": "股票评级记录",
    "description": "股票评级记录数据",
    "route": "/stocks/collections/stock_institute_recommend_detail",
    "fields": [],
},
{
    "name": "stock_intraday_em",
    "display_name": "日内分时数据-东财",
    "description": "日内分时数据-东财数据",
    "route": "/stocks/collections/stock_intraday_em",
    "fields": [],
},
{
    "name": "stock_intraday_sina",
    "display_name": "日内分时数据-新浪",
    "description": "日内分时数据-新浪数据",
    "route": "/stocks/collections/stock_intraday_sina",
    "fields": [],
},
{
    "name": "stock_ipo_benefit_ths",
    "display_name": "IPO 受益股",
    "description": "IPO 受益股数据",
    "route": "/stocks/collections/stock_ipo_benefit_ths",
    "fields": [],
},
{
    "name": "stock_ipo_declare",
    "display_name": "首发申报信息",
    "description": "首发申报信息数据",
    "route": "/stocks/collections/stock_ipo_declare",
    "fields": [],
},
{
    "name": "stock_ipo_summary_cninfo",
    "display_name": "上市相关-巨潮资讯",
    "description": "上市相关-巨潮资讯数据",
    "route": "/stocks/collections/stock_ipo_summary_cninfo",
    "fields": [],
},
{
    "name": "stock_irm_ans_cninfo",
    "display_name": "互动易-回答",
    "description": "互动易-回答数据",
    "route": "/stocks/collections/stock_irm_ans_cninfo",
    "fields": [],
},
{
    "name": "stock_irm_cninfo",
    "display_name": "互动易-提问",
    "description": "互动易-提问数据",
    "route": "/stocks/collections/stock_irm_cninfo",
    "fields": [],
},
{
    "name": "stock_kc_a_spot_em",
    "display_name": "科创板",
    "description": "科创板数据",
    "route": "/stocks/collections/stock_kc_a_spot_em",
    "fields": [],
},
{
    "name": "stock_lh_yyb_capital",
    "display_name": "龙虎榜-营业部排行-资金实力最强",
    "description": "龙虎榜-营业部排行-资金实力最强数据",
    "route": "/stocks/collections/stock_lh_yyb_capital",
    "fields": [],
},
{
    "name": "stock_lh_yyb_control",
    "display_name": "龙虎榜-营业部排行-抱团操作实力",
    "description": "龙虎榜-营业部排行-抱团操作实力数据",
    "route": "/stocks/collections/stock_lh_yyb_control",
    "fields": [],
},
{
    "name": "stock_lh_yyb_most",
    "display_name": "龙虎榜-营业部排行-上榜次数最多",
    "description": "龙虎榜-营业部排行-上榜次数最多数据",
    "route": "/stocks/collections/stock_lh_yyb_most",
    "fields": [],
},
{
    "name": "stock_lhb_detail_daily_sina",
    "display_name": "龙虎榜-每日详情",
    "description": "龙虎榜-每日详情数据",
    "route": "/stocks/collections/stock_lhb_detail_daily_sina",
    "fields": [],
},
{
    "name": "stock_lhb_detail_em",
    "display_name": "龙虎榜详情",
    "description": "龙虎榜详情数据",
    "route": "/stocks/collections/stock_lhb_detail_em",
    "fields": [],
},
{
    "name": "stock_lhb_ggtj_sina",
    "display_name": "龙虎榜-个股上榜统计",
    "description": "龙虎榜-个股上榜统计数据",
    "route": "/stocks/collections/stock_lhb_ggtj_sina",
    "fields": [],
},
{
    "name": "stock_lhb_hyyyb_em",
    "display_name": "每日活跃营业部",
    "description": "每日活跃营业部数据",
    "route": "/stocks/collections/stock_lhb_hyyyb_em",
    "fields": [],
},
{
    "name": "stock_lhb_jgmmtj_em",
    "display_name": "机构买卖每日统计",
    "description": "机构买卖每日统计数据",
    "route": "/stocks/collections/stock_lhb_jgmmtj_em",
    "fields": [],
},
{
    "name": "stock_lhb_jgmx_sina",
    "display_name": "龙虎榜-机构席位成交明细",
    "description": "龙虎榜-机构席位成交明细数据",
    "route": "/stocks/collections/stock_lhb_jgmx_sina",
    "fields": [],
},
{
    "name": "stock_lhb_jgstatistic_em",
    "display_name": "机构席位追踪",
    "description": "机构席位追踪数据",
    "route": "/stocks/collections/stock_lhb_jgstatistic_em",
    "fields": [],
},
{
    "name": "stock_lhb_jgzz_sina",
    "display_name": "龙虎榜-机构席位追踪",
    "description": "龙虎榜-机构席位追踪数据",
    "route": "/stocks/collections/stock_lhb_jgzz_sina",
    "fields": [],
},
{
    "name": "stock_lhb_stock_detail_em",
    "display_name": "个股龙虎榜详情",
    "description": "个股龙虎榜详情数据",
    "route": "/stocks/collections/stock_lhb_stock_detail_em",
    "fields": [],
},
{
    "name": "stock_lhb_stock_statistic_em",
    "display_name": "个股上榜统计",
    "description": "个股上榜统计数据",
    "route": "/stocks/collections/stock_lhb_stock_statistic_em",
    "fields": [],
},
{
    "name": "stock_lhb_traderstatistic_em",
    "display_name": "营业部统计",
    "description": "营业部统计数据",
    "route": "/stocks/collections/stock_lhb_traderstatistic_em",
    "fields": [],
},
{
    "name": "stock_lhb_yyb_detail_em",
    "display_name": "营业部详情数据-东财",
    "description": "营业部详情数据-东财数据",
    "route": "/stocks/collections/stock_lhb_yyb_detail_em",
    "fields": [],
},
{
    "name": "stock_lhb_yybph_em",
    "display_name": "营业部排行",
    "description": "营业部排行数据",
    "route": "/stocks/collections/stock_lhb_yybph_em",
    "fields": [],
},
{
    "name": "stock_lhb_yytj_sina",
    "display_name": "龙虎榜-营业上榜统计",
    "description": "龙虎榜-营业上榜统计数据",
    "route": "/stocks/collections/stock_lhb_yytj_sina",
    "fields": [],
},
{
    "name": "stock_lrb_em",
    "display_name": "利润表",
    "description": "利润表数据",
    "route": "/stocks/collections/stock_lrb_em",
    "fields": [],
},
{
    "name": "stock_main_stock_holder",
    "display_name": "主要股东",
    "description": "主要股东数据",
    "route": "/stocks/collections/stock_main_stock_holder",
    "fields": [],
},
{
    "name": "stock_margin_account_info",
    "display_name": "两融账户信息",
    "description": "两融账户信息数据",
    "route": "/stocks/collections/stock_margin_account_info",
    "fields": [],
},
{
    "name": "stock_margin_detail_sse",
    "display_name": "融资融券明细",
    "description": "融资融券明细数据",
    "route": "/stocks/collections/stock_margin_detail_sse",
    "fields": [],
},
{
    "name": "stock_margin_detail_szse",
    "display_name": "融资融券明细",
    "description": "融资融券明细数据",
    "route": "/stocks/collections/stock_margin_detail_szse",
    "fields": [],
},
{
    "name": "stock_margin_ratio_pa",
    "display_name": "标的证券名单及保证金比例查询",
    "description": "标的证券名单及保证金比例查询数据",
    "route": "/stocks/collections/stock_margin_ratio_pa",
    "fields": [],
},
{
    "name": "stock_margin_sse",
    "display_name": "融资融券汇总",
    "description": "融资融券汇总数据",
    "route": "/stocks/collections/stock_margin_sse",
    "fields": [],
},
{
    "name": "stock_margin_szse",
    "display_name": "融资融券汇总",
    "description": "融资融券汇总数据",
    "route": "/stocks/collections/stock_margin_szse",
    "fields": [],
},
{
    "name": "stock_margin_underlying_info_szse",
    "display_name": "标的证券信息",
    "description": "标的证券信息数据",
    "route": "/stocks/collections/stock_margin_underlying_info_szse",
    "fields": [],
},
{
    "name": "stock_market_activity_legu",
    "display_name": "赚钱效应分析",
    "description": "赚钱效应分析数据",
    "route": "/stocks/collections/stock_market_activity_legu",
    "fields": [],
},
{
    "name": "stock_market_pb_lg",
    "display_name": "主板市净率",
    "description": "主板市净率数据",
    "route": "/stocks/collections/stock_market_pb_lg",
    "fields": [],
},
{
    "name": "stock_market_pe_lg",
    "display_name": "主板市盈率",
    "description": "主板市盈率数据",
    "route": "/stocks/collections/stock_market_pe_lg",
    "fields": [],
},
{
    "name": "stock_new_a_spot_em",
    "display_name": "新股",
    "description": "新股数据",
    "route": "/stocks/collections/stock_new_a_spot_em",
    "fields": [],
},
{
    "name": "stock_new_gh_cninfo",
    "display_name": "新股过会",
    "description": "新股过会数据",
    "route": "/stocks/collections/stock_new_gh_cninfo",
    "fields": [],
},
{
    "name": "stock_new_ipo_cninfo",
    "display_name": "新股发行",
    "description": "新股发行数据",
    "route": "/stocks/collections/stock_new_ipo_cninfo",
    "fields": [],
},
{
    "name": "stock_news_main_cx",
    "display_name": "财经内容精选",
    "description": "财经内容精选数据",
    "route": "/stocks/collections/stock_news_main_cx",
    "fields": [],
},
{
    "name": "stock_pg_em",
    "display_name": "配股",
    "description": "配股数据",
    "route": "/stocks/collections/stock_pg_em",
    "fields": [],
},
{
    "name": "stock_price_js",
    "display_name": "美港目标价",
    "description": "美港目标价数据",
    "route": "/stocks/collections/stock_price_js",
    "fields": [],
},
{
    "name": "stock_profile_cninfo",
    "display_name": "公司概况-巨潮资讯",
    "description": "公司概况-巨潮资讯数据",
    "route": "/stocks/collections/stock_profile_cninfo",
    "fields": [],
},
{
    "name": "stock_profit_forecast_em",
    "display_name": "盈利预测-东方财富",
    "description": "盈利预测-东方财富数据",
    "route": "/stocks/collections/stock_profit_forecast_em",
    "fields": [],
},
{
    "name": "stock_profit_forecast_ths",
    "display_name": "盈利预测-同花顺",
    "description": "盈利预测-同花顺数据",
    "route": "/stocks/collections/stock_profit_forecast_ths",
    "fields": [],
},
{
    "name": "stock_profit_sheet_by_report_em",
    "display_name": "利润表-按报告期",
    "description": "利润表-按报告期数据",
    "route": "/stocks/collections/stock_profit_sheet_by_report_em",
    "fields": [],
},
{
    "name": "stock_profit_sheet_by_yearly_em",
    "display_name": "利润表-按年度",
    "description": "利润表-按年度数据",
    "route": "/stocks/collections/stock_profit_sheet_by_yearly_em",
    "fields": [],
},
{
    "name": "stock_qbzf_em",
    "display_name": "增发",
    "description": "增发数据",
    "route": "/stocks/collections/stock_qbzf_em",
    "fields": [],
},
{
    "name": "stock_qsjy_em",
    "display_name": "券商业绩月报",
    "description": "券商业绩月报数据",
    "route": "/stocks/collections/stock_qsjy_em",
    "fields": [],
},
{
    "name": "stock_rank_cxfl_ths",
    "display_name": "持续放量",
    "description": "持续放量数据",
    "route": "/stocks/collections/stock_rank_cxfl_ths",
    "fields": [],
},
{
    "name": "stock_rank_cxsl_ths",
    "display_name": "持续缩量",
    "description": "持续缩量数据",
    "route": "/stocks/collections/stock_rank_cxsl_ths",
    "fields": [],
},
{
    "name": "stock_rank_forecast_cninfo",
    "display_name": "投资评级",
    "description": "投资评级数据",
    "route": "/stocks/collections/stock_rank_forecast_cninfo",
    "fields": [],
},
{
    "name": "stock_rank_ljqd_ths",
    "display_name": "量价齐跌",
    "description": "量价齐跌数据",
    "route": "/stocks/collections/stock_rank_ljqd_ths",
    "fields": [],
},
{
    "name": "stock_rank_ljqs_ths",
    "display_name": "量价齐升",
    "description": "量价齐升数据",
    "route": "/stocks/collections/stock_rank_ljqs_ths",
    "fields": [],
},
{
    "name": "stock_rank_xstp_ths",
    "display_name": "向上突破",
    "description": "向上突破数据",
    "route": "/stocks/collections/stock_rank_xstp_ths",
    "fields": [],
},
{
    "name": "stock_rank_xxtp_ths",
    "display_name": "向下突破",
    "description": "向下突破数据",
    "route": "/stocks/collections/stock_rank_xxtp_ths",
    "fields": [],
},
{
    "name": "stock_rank_xzjp_ths",
    "display_name": "险资举牌",
    "description": "险资举牌数据",
    "route": "/stocks/collections/stock_rank_xzjp_ths",
    "fields": [],
},
{
    "name": "stock_register_bj",
    "display_name": "北交所",
    "description": "北交所数据",
    "route": "/stocks/collections/stock_register_bj",
    "fields": [],
},
{
    "name": "stock_register_cyb",
    "display_name": "创业板",
    "description": "创业板数据",
    "route": "/stocks/collections/stock_register_cyb",
    "fields": [],
},
{
    "name": "stock_register_db",
    "display_name": "达标企业",
    "description": "达标企业数据",
    "route": "/stocks/collections/stock_register_db",
    "fields": [],
},
{
    "name": "stock_register_kcb",
    "display_name": "科创板",
    "description": "科创板数据",
    "route": "/stocks/collections/stock_register_kcb",
    "fields": [],
},
{
    "name": "stock_register_sh",
    "display_name": "上海主板",
    "description": "上海主板数据",
    "route": "/stocks/collections/stock_register_sh",
    "fields": [],
},
{
    "name": "stock_register_sz",
    "display_name": "深圳主板",
    "description": "深圳主板数据",
    "route": "/stocks/collections/stock_register_sz",
    "fields": [],
},
{
    "name": "stock_report_disclosure",
    "display_name": "预约披露时间-巨潮资讯",
    "description": "预约披露时间-巨潮资讯数据",
    "route": "/stocks/collections/stock_report_disclosure",
    "fields": [],
},
{
    "name": "stock_report_fund_hold",
    "display_name": "基金持股",
    "description": "基金持股数据",
    "route": "/stocks/collections/stock_report_fund_hold",
    "fields": [],
},
{
    "name": "stock_report_fund_hold_detail",
    "display_name": "基金持股明细",
    "description": "基金持股明细数据",
    "route": "/stocks/collections/stock_report_fund_hold_detail",
    "fields": [],
},
{
    "name": "stock_repurchase_em",
    "display_name": "股票回购数据",
    "description": "股票回购数据数据",
    "route": "/stocks/collections/stock_repurchase_em",
    "fields": [],
},
{
    "name": "stock_restricted_release_detail_em",
    "display_name": "限售股解禁详情",
    "description": "限售股解禁详情数据",
    "route": "/stocks/collections/stock_restricted_release_detail_em",
    "fields": [],
},
{
    "name": "stock_restricted_release_queue_sina",
    "display_name": "个股限售解禁-新浪",
    "description": "个股限售解禁-新浪数据",
    "route": "/stocks/collections/stock_restricted_release_queue_sina",
    "fields": [],
},
{
    "name": "stock_restricted_release_stockholder_em",
    "display_name": "解禁股东",
    "description": "解禁股东数据",
    "route": "/stocks/collections/stock_restricted_release_stockholder_em",
    "fields": [],
},
{
    "name": "stock_restricted_release_summary_em",
    "display_name": "限售股解禁",
    "description": "限售股解禁数据",
    "route": "/stocks/collections/stock_restricted_release_summary_em",
    "fields": [],
},
{
    "name": "stock_sector_detail",
    "display_name": "板块详情",
    "description": "板块详情数据",
    "route": "/stocks/collections/stock_sector_detail",
    "fields": [],
},
{
    "name": "stock_sector_spot",
    "display_name": "板块行情",
    "description": "板块行情数据",
    "route": "/stocks/collections/stock_sector_spot",
    "fields": [],
},
{
    "name": "stock_sgt_settlement_exchange_rate_sse",
    "display_name": "结算汇率-沪港通",
    "description": "结算汇率-沪港通数据",
    "route": "/stocks/collections/stock_sgt_settlement_exchange_rate_sse",
    "fields": [],
},
{
    "name": "stock_sgt_settlement_exchange_rate_szse",
    "display_name": "结算汇率-深港通",
    "description": "结算汇率-深港通数据",
    "route": "/stocks/collections/stock_sgt_settlement_exchange_rate_szse",
    "fields": [],
},
{
    "name": "stock_sh_a_spot_em",
    "display_name": "沪 A 股",
    "description": "沪 A 股数据",
    "route": "/stocks/collections/stock_sh_a_spot_em",
    "fields": [],
},
{
    "name": "stock_share_change_cninfo",
    "display_name": "公司股本变动-巨潮资讯",
    "description": "公司股本变动-巨潮资讯数据",
    "route": "/stocks/collections/stock_share_change_cninfo",
    "fields": [],
},
{
    "name": "stock_share_hold_change_bse",
    "display_name": "董监高及相关人员持股变动-北证",
    "description": "董监高及相关人员持股变动-北证数据",
    "route": "/stocks/collections/stock_share_hold_change_bse",
    "fields": [],
},
{
    "name": "stock_share_hold_change_sse",
    "display_name": "董监高及相关人员持股变动-上证",
    "description": "董监高及相关人员持股变动-上证数据",
    "route": "/stocks/collections/stock_share_hold_change_sse",
    "fields": [],
},
{
    "name": "stock_share_hold_change_szse",
    "display_name": "董监高及相关人员持股变动-深证",
    "description": "董监高及相关人员持股变动-深证数据",
    "route": "/stocks/collections/stock_share_hold_change_szse",
    "fields": [],
},
{
    "name": "stock_sns_sseinfo",
    "display_name": "上证e互动",
    "description": "上证e互动数据",
    "route": "/stocks/collections/stock_sns_sseinfo",
    "fields": [],
},
{
    "name": "stock_sse_deal_daily",
    "display_name": "上海证券交易所-每日概况",
    "description": "上海证券交易所-每日概况数据",
    "route": "/stocks/collections/stock_sse_deal_daily",
    "fields": [],
},
{
    "name": "stock_sse_summary",
    "display_name": "上海证券交易所",
    "description": "上海证券交易所数据",
    "route": "/stocks/collections/stock_sse_summary",
    "fields": [],
},
{
    "name": "stock_staq_net_stop",
    "display_name": "两网及退市",
    "description": "两网及退市数据",
    "route": "/stocks/collections/stock_staq_net_stop",
    "fields": [],
},
{
    "name": "stock_sy_em",
    "display_name": "个股商誉明细",
    "description": "个股商誉明细数据",
    "route": "/stocks/collections/stock_sy_em",
    "fields": [],
},
{
    "name": "stock_sy_hy_em",
    "display_name": "行业商誉",
    "description": "行业商誉数据",
    "route": "/stocks/collections/stock_sy_hy_em",
    "fields": [],
},
{
    "name": "stock_sy_jz_em",
    "display_name": "个股商誉减值明细",
    "description": "个股商誉减值明细数据",
    "route": "/stocks/collections/stock_sy_jz_em",
    "fields": [],
},
{
    "name": "stock_sy_profile_em",
    "display_name": "A股商誉市场概况",
    "description": "A股商誉市场概况数据",
    "route": "/stocks/collections/stock_sy_profile_em",
    "fields": [],
},
{
    "name": "stock_sy_yq_em",
    "display_name": "商誉减值预期明细",
    "description": "商誉减值预期明细数据",
    "route": "/stocks/collections/stock_sy_yq_em",
    "fields": [],
},
{
    "name": "stock_sz_a_spot_em",
    "display_name": "深 A 股",
    "description": "深 A 股数据",
    "route": "/stocks/collections/stock_sz_a_spot_em",
    "fields": [],
},
{
    "name": "stock_szse_area_summary",
    "display_name": "地区交易排序",
    "description": "地区交易排序数据",
    "route": "/stocks/collections/stock_szse_area_summary",
    "fields": [],
},
{
    "name": "stock_szse_sector_summary",
    "display_name": "股票行业成交",
    "description": "股票行业成交数据",
    "route": "/stocks/collections/stock_szse_sector_summary",
    "fields": [],
},
{
    "name": "stock_szse_summary",
    "display_name": "证券类别统计",
    "description": "证券类别统计数据",
    "route": "/stocks/collections/stock_szse_summary",
    "fields": [],
},
{
    "name": "stock_us_daily",
    "display_name": "历史行情数据-新浪",
    "description": "历史行情数据-新浪数据",
    "route": "/stocks/collections/stock_us_daily",
    "fields": [],
},
{
    "name": "stock_us_famous_spot_em",
    "display_name": "知名美股",
    "description": "知名美股数据",
    "route": "/stocks/collections/stock_us_famous_spot_em",
    "fields": [],
},
{
    "name": "stock_us_hist",
    "display_name": "历史行情数据-东财",
    "description": "历史行情数据-东财数据",
    "route": "/stocks/collections/stock_us_hist",
    "fields": [],
},
{
    "name": "stock_us_hist_min_em",
    "display_name": "分时数据-东财",
    "description": "分时数据-东财数据",
    "route": "/stocks/collections/stock_us_hist_min_em",
    "fields": [],
},
{
    "name": "stock_us_pink_spot_em",
    "display_name": "粉单市场",
    "description": "粉单市场数据",
    "route": "/stocks/collections/stock_us_pink_spot_em",
    "fields": [],
},
{
    "name": "stock_us_spot",
    "display_name": "实时行情数据-新浪",
    "description": "实时行情数据-新浪数据",
    "route": "/stocks/collections/stock_us_spot",
    "fields": [],
},
{
    "name": "stock_us_spot_em",
    "display_name": "实时行情数据-东财",
    "description": "实时行情数据-东财数据",
    "route": "/stocks/collections/stock_us_spot_em",
    "fields": [],
},
{
    "name": "stock_value_em",
    "display_name": "个股估值",
    "description": "个股估值数据",
    "route": "/stocks/collections/stock_value_em",
    "fields": [],
},
{
    "name": "stock_xgsr_ths",
    "display_name": "新股上市首日",
    "description": "新股上市首日数据",
    "route": "/stocks/collections/stock_xgsr_ths",
    "fields": [],
},
{
    "name": "stock_xjll_em",
    "display_name": "现金流量表",
    "description": "现金流量表数据",
    "route": "/stocks/collections/stock_xjll_em",
    "fields": [],
},
{
    "name": "stock_yjbb_em",
    "display_name": "业绩报表",
    "description": "业绩报表数据",
    "route": "/stocks/collections/stock_yjbb_em",
    "fields": [],
},
{
    "name": "stock_yjkb_em",
    "display_name": "业绩快报",
    "description": "业绩快报数据",
    "route": "/stocks/collections/stock_yjkb_em",
    "fields": [],
},
{
    "name": "stock_yzxdr_em",
    "display_name": "一致行动人",
    "description": "一致行动人数据",
    "route": "/stocks/collections/stock_yzxdr_em",
    "fields": [],
},
{
    "name": "stock_zcfz_bj_em",
    "display_name": "资产负债表-北交所",
    "description": "资产负债表-北交所数据",
    "route": "/stocks/collections/stock_zcfz_bj_em",
    "fields": [],
},
{
    "name": "stock_zcfz_em",
    "display_name": "资产负债表-沪深",
    "description": "资产负债表-沪深数据",
    "route": "/stocks/collections/stock_zcfz_em",
    "fields": [],
},
{
    "name": "stock_zh_a_cdr_daily",
    "display_name": "历史行情数据",
    "description": "历史行情数据数据",
    "route": "/stocks/collections/stock_zh_a_cdr_daily",
    "fields": [],
},
{
    "name": "stock_zh_a_daily",
    "display_name": "历史行情数据-新浪",
    "description": "历史行情数据-新浪数据",
    "route": "/stocks/collections/stock_zh_a_daily",
    "fields": [],
},
{
    "name": "stock_zh_a_disclosure_relation_cninfo",
    "display_name": "信息披露调研-巨潮资讯",
    "description": "信息披露调研-巨潮资讯数据",
    "route": "/stocks/collections/stock_zh_a_disclosure_relation_cninfo",
    "fields": [],
},
{
    "name": "stock_zh_a_disclosure_report_cninfo",
    "display_name": "信息披露公告-巨潮资讯",
    "description": "信息披露公告-巨潮资讯数据",
    "route": "/stocks/collections/stock_zh_a_disclosure_report_cninfo",
    "fields": [],
},
{
    "name": "stock_zh_a_gbjg_em",
    "display_name": "股本结构",
    "description": "股本结构数据",
    "route": "/stocks/collections/stock_zh_a_gbjg_em",
    "fields": [],
},
{
    "name": "stock_zh_a_gdhs",
    "display_name": "股东户数",
    "description": "股东户数数据",
    "route": "/stocks/collections/stock_zh_a_gdhs",
    "fields": [],
},
{
    "name": "stock_zh_a_gdhs_detail_em",
    "display_name": "股东户数详情",
    "description": "股东户数详情数据",
    "route": "/stocks/collections/stock_zh_a_gdhs_detail_em",
    "fields": [],
},
{
    "name": "stock_zh_a_hist",
    "display_name": "A股历史行情-东财",
    "description": "A股历史行情-东财数据",
    "route": "/stocks/collections/stock_zh_a_hist",
    "fields": [],
},
{
    "name": "stock_zh_a_hist_min_em",
    "display_name": "A股分时数据-东财",
    "description": "A股分时数据-东财数据",
    "route": "/stocks/collections/stock_zh_a_hist_min_em",
    "fields": [],
},
{
    "name": "stock_zh_a_hist_pre_min_em",
    "display_name": "盘前数据",
    "description": "盘前数据数据",
    "route": "/stocks/collections/stock_zh_a_hist_pre_min_em",
    "fields": [],
},
{
    "name": "stock_zh_a_hist_tx",
    "display_name": "历史行情数据-腾讯",
    "description": "历史行情数据-腾讯数据",
    "route": "/stocks/collections/stock_zh_a_hist_tx",
    "fields": [],
},
{
    "name": "stock_zh_a_minute",
    "display_name": "分时数据-新浪",
    "description": "分时数据-新浪数据",
    "route": "/stocks/collections/stock_zh_a_minute",
    "fields": [],
},
{
    "name": "stock_zh_a_new_em",
    "display_name": "新股",
    "description": "新股数据",
    "route": "/stocks/collections/stock_zh_a_new_em",
    "fields": [],
},
{
    "name": "stock_zh_a_spot",
    "display_name": "实时行情数据-新浪",
    "description": "实时行情数据-新浪数据",
    "route": "/stocks/collections/stock_zh_a_spot",
    "fields": [],
},
{
    "name": "stock_zh_a_spot_em",
    "display_name": "沪深京A股实时行情-东财",
    "description": "沪深京A股实时行情-东财数据",
    "route": "/stocks/collections/stock_zh_a_spot_em",
    "fields": [],
},
{
    "name": "stock_zh_a_st_em",
    "display_name": "风险警示板",
    "description": "风险警示板数据",
    "route": "/stocks/collections/stock_zh_a_st_em",
    "fields": [],
},
{
    "name": "stock_zh_a_stop_em",
    "display_name": "两网及退市",
    "description": "两网及退市数据",
    "route": "/stocks/collections/stock_zh_a_stop_em",
    "fields": [],
},
{
    "name": "stock_zh_a_tick_tx",
    "display_name": "腾讯财经",
    "description": "腾讯财经数据",
    "route": "/stocks/collections/stock_zh_a_tick_tx",
    "fields": [],
},
{
    "name": "stock_zh_ab_comparison_em",
    "display_name": "AB 股比价",
    "description": "AB 股比价数据",
    "route": "/stocks/collections/stock_zh_ab_comparison_em",
    "fields": [],
},
{
    "name": "stock_zh_ah_daily",
    "display_name": "历史行情数据",
    "description": "历史行情数据数据",
    "route": "/stocks/collections/stock_zh_ah_daily",
    "fields": [],
},
{
    "name": "stock_zh_ah_name",
    "display_name": "A+H股票字典",
    "description": "A+H股票字典数据",
    "route": "/stocks/collections/stock_zh_ah_name",
    "fields": [],
},
{
    "name": "stock_zh_ah_spot",
    "display_name": "实时行情数据-腾讯",
    "description": "实时行情数据-腾讯数据",
    "route": "/stocks/collections/stock_zh_ah_spot",
    "fields": [],
},
{
    "name": "stock_zh_ah_spot_em",
    "display_name": "实时行情数据-东财",
    "description": "实时行情数据-东财数据",
    "route": "/stocks/collections/stock_zh_ah_spot_em",
    "fields": [],
},
{
    "name": "stock_zh_b_daily",
    "display_name": "历史行情数据",
    "description": "历史行情数据数据",
    "route": "/stocks/collections/stock_zh_b_daily",
    "fields": [],
},
{
    "name": "stock_zh_b_minute",
    "display_name": "分时数据",
    "description": "分时数据数据",
    "route": "/stocks/collections/stock_zh_b_minute",
    "fields": [],
},
{
    "name": "stock_zh_b_spot",
    "display_name": "实时行情数据-新浪",
    "description": "实时行情数据-新浪数据",
    "route": "/stocks/collections/stock_zh_b_spot",
    "fields": [],
},
{
    "name": "stock_zh_b_spot_em",
    "display_name": "实时行情数据-东财",
    "description": "实时行情数据-东财数据",
    "route": "/stocks/collections/stock_zh_b_spot_em",
    "fields": [],
},
{
    "name": "stock_zh_dupont_comparison_em",
    "display_name": "杜邦分析比较",
    "description": "杜邦分析比较数据",
    "route": "/stocks/collections/stock_zh_dupont_comparison_em",
    "fields": [],
},
{
    "name": "stock_zh_growth_comparison_em",
    "display_name": "成长性比较",
    "description": "成长性比较数据",
    "route": "/stocks/collections/stock_zh_growth_comparison_em",
    "fields": [],
},
{
    "name": "stock_zh_kcb_daily",
    "display_name": "历史行情数据",
    "description": "历史行情数据数据",
    "route": "/stocks/collections/stock_zh_kcb_daily",
    "fields": [],
},
{
    "name": "stock_zh_kcb_report_em",
    "display_name": "科创板公告",
    "description": "科创板公告数据",
    "route": "/stocks/collections/stock_zh_kcb_report_em",
    "fields": [],
},
{
    "name": "stock_zh_kcb_spot",
    "display_name": "实时行情数据",
    "description": "实时行情数据数据",
    "route": "/stocks/collections/stock_zh_kcb_spot",
    "fields": [],
},
{
    "name": "stock_zh_scale_comparison_em",
    "display_name": "公司规模",
    "description": "公司规模数据",
    "route": "/stocks/collections/stock_zh_scale_comparison_em",
    "fields": [],
},
{
    "name": "stock_zh_valuation_baidu",
    "display_name": "A 股估值指标",
    "description": "A 股估值指标数据",
    "route": "/stocks/collections/stock_zh_valuation_baidu",
    "fields": [],
},
{
    "name": "stock_zh_valuation_comparison_em",
    "display_name": "估值比较",
    "description": "估值比较数据",
    "route": "/stocks/collections/stock_zh_valuation_comparison_em",
    "fields": [],
},
{
    "name": "stock_zh_vote_baidu",
    "display_name": "涨跌投票",
    "description": "涨跌投票数据",
    "route": "/stocks/collections/stock_zh_vote_baidu",
    "fields": [],
},
{
    "name": "stock_zt_pool_dtgc_em",
    "display_name": "跌停股池",
    "description": "跌停股池数据",
    "route": "/stocks/collections/stock_zt_pool_dtgc_em",
    "fields": [],
},
{
    "name": "stock_zt_pool_em",
    "display_name": "涨停股池",
    "description": "涨停股池数据",
    "route": "/stocks/collections/stock_zt_pool_em",
    "fields": [],
},
{
    "name": "stock_zt_pool_previous_em",
    "display_name": "昨日涨停股池",
    "description": "昨日涨停股池数据",
    "route": "/stocks/collections/stock_zt_pool_previous_em",
    "fields": [],
},
{
    "name": "stock_zt_pool_strong_em",
    "display_name": "强势股池",
    "description": "强势股池数据",
    "route": "/stocks/collections/stock_zt_pool_strong_em",
    "fields": [],
},
{
    "name": "stock_zt_pool_sub_new_em",
    "display_name": "次新股池",
    "description": "次新股池数据",
    "route": "/stocks/collections/stock_zt_pool_sub_new_em",
    "fields": [],
},
{
    "name": "stock_zt_pool_zbgc_em",
    "display_name": "炸板股池",
    "description": "炸板股池数据",
    "route": "/stocks/collections/stock_zt_pool_zbgc_em",
    "fields": [],
},
{
    "name": "stock_zygc_em",
    "display_name": "主营构成-东财",
    "description": "主营构成-东财数据",
    "route": "/stocks/collections/stock_zygc_em",
    "fields": [],
},
{
    "name": "stock_zyjs_ths",
    "display_name": "主营介绍-同花顺",
    "description": "主营介绍-同花顺数据",
    "route": "/stocks/collections/stock_zyjs_ths",
    "fields": [],
},
]
